eseller_suite/eseller_suite/doctype/amazon_seller_central_settings/amazon_seller_central_settings.js
eseller_suite/eseller_suite/doctype/amazon_seller_central_settings/amazon_seller_central_settings.json
eseller_suite/eseller_suite/doctype/amazon_seller_central_settings/amazon_seller_central_settings.py
eseller_suite/eseller_suite/doctype/amazon_seller_central_settings/test_amazon_seller_central_settings.py

Amazon Seller Central Settings
- Chrome

feat: Amazon Seller Central Settings

---

eseller_suite/eseller_suite/doctype/amazon_seller_central_settings/amazon_seller_central_settings.json
eseller_suite/eseller_suite/doctype/amazon_seller_central_settings/amazon_seller_central_settings.py

Access token generation
- Chrome

feat: Access token generation

---

eseller_suite/eseller_suite/doctype/amazon_seller_central_settings/amazon_seller_central_settings.js
eseller_suite/eseller_suite/doctype/amazon_seller_central_settings/amazon_seller_central_settings.py

feat: Amazon Api

---

eseller_suite/eseller_suite/doctype/amazon_seller_central_settings/amazon_seller_central_settings.py

- Create Sales Invoice for first 5 Orders Amazon Products.
- Chrome

feat: Create Sales Invoice for Amazon Orders.

---

eseller_suite/eseller_suite/doctype/amazon_seller_central_settings/amazon_seller_central_settings.js
eseller_suite/eseller_suite/doctype/amazon_seller_central_settings/amazon_seller_central_settings.json
eseller_suite/eseller_suite/doctype/amazon_seller_central_settings/amazon_seller_central_settings.py
eseller_suite/eseller_suite/workspace/eseller_suite/eseller_suite.json

fetching Orders with limit
No
- Chrome

feat: fetching Orders with limit

---

eseller_suite/eseller_suite/doctype/amazon_fields_map/amazon_fields_map.json
eseller_suite/eseller_suite/doctype/amazon_fields_map/amazon_fields_map.py
eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_repository.py
eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_sp_api.py
eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_sp_api_settings.js
eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_sp_api_settings.json
eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_sp_api_settings.py
eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/test_amazon_sp_api_settings.py
eseller_suite/eseller_suite/workspace/eseller_suite/eseller_suite.json
eseller_suite/hooks.py

feat: SO syncing realtime

---

eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_repository.py

Get Order Financial Events
No.
- Chrome

fix:Get Order Financial Events

---

eseller_suite/eseller_suite/doctype/amazon_payment_extractor/amazon_payment_extractor.py
eseller_suite/eseller_suite/doctype/amazon_seller_central_settings/amazon_seller_central_settings.py

Change field name in Sales Invoice
No.
- Chrome

fix:Change field name in Sales Invoice

---

eseller_suite/eseller_suite/doctype/amazon_failed_sync_record/amazon_failed_sync_record.json
eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_repository.py
eseller_suite/eseller_suite/doctype/amazon_state_mapping/amazon_state_mapping.json
eseller_suite/fixtures/amazon_state_mapping.json

Sales Order syncing
No
- Chrome

fix: Sales Order syncing

---

eseller_suite/eseller_suite/report/amazon_sales_report/amazon_sales_report.js
eseller_suite/eseller_suite/report/amazon_sales_report/amazon_sales_report.json
eseller_suite/eseller_suite/report/amazon_sales_report/amazon_sales_report.py
eseller_suite/eseller_suite/workspace/eseller_suite/eseller_suite.json

Amazon Sales Report
No
- Chrome

feat: Amazon Sales Report

---

eseller_suite/eseller_suite/doctype/amazon_payment_tool/amazon_payment_tool.js
eseller_suite/eseller_suite/doctype/amazon_payment_tool/amazon_payment_tool.json
eseller_suite/eseller_suite/doctype/amazon_payment_tool/amazon_payment_tool.py
eseller_suite/eseller_suite/doctype/amazon_payment_tool_item/amazon_payment_tool_item.json
eseller_suite/eseller_suite/workspace/eseller_suite/eseller_suite.json

Amazon Payment Tool
No
- Chrome

feat: Amazon Payment Tool

---

eseller_suite/eseller_suite/doctype/amazon_payment_entry/amazon_payment_entry.py

When uploading a file in Amazon Payment Entry:
The error is due to differently encoded file.
Pass the encoding of the file when reading the file
Amazon Payment Entry
No
- Chrome
- Opera Mini
- Safari

fix: handled encoding issues in amazon payment entry

---

eseller_suite/eseller_suite/custom_script/sales_invoice/sales_invoice.py
eseller_suite/hooks.py

Auto serial no updation on sales invoice if has serial no item
Clearly and concisely describe the feature.
Analyse and attach the design documentation
Describe your code changes in detail for reviewers.
Post the output screenshots, if a UI is affected or added due to this feature.
List out the areas affected by your code changes.
Mention Yes or No. If Yes, provide the appropriate explanation.
- Chrome
- Opera Mini
- Safari

fix: Auto update serial no from sales invoice

---

eseller_suite/eseller_suite/custom_script/purchase_receipt/purchase_receipt.py
eseller_suite/eseller_suite/custom_script/stock_entry/stock_entry.py
eseller_suite/eseller_suite/doctype/eseller_serial_no/eseller_serial_no.js
eseller_suite/eseller_suite/doctype/eseller_serial_no/eseller_serial_no.json
eseller_suite/eseller_suite/doctype/eseller_serial_no/eseller_serial_no.py
eseller_suite/eseller_suite/doctype/eseller_serial_no/test_eseller_serial_no.py
eseller_suite/eseller_suite/doctype/eseller_settings/eseller_settings.json
eseller_suite/eseller_suite/report/eseller_serial_no_report/eseller_serial_no_report.json
eseller_suite/hooks.py
eseller_suite/setup.py

Replaced the Serial/Batch Nos with a custom feature
Added Requried doctypes, scripts and reports
List out the areas affected by your code changes.
Mention Yes or No. If Yes, provide the appropriate explanation.
- Chrome
- Opera Mini
- Safari

feat: eSeller Serial Nos

---

eseller_suite/eseller_suite/custom_script/purchase_receipt/purchase_receipt.py
eseller_suite/eseller_suite/custom_script/stock_entry/stock_entry.py

Don't need alerts for each Serial Number
Removed alerts for each serial number for each item and gave one for each of creating and updating serial numbers

fix: removed repeating alerts

---

eseller_suite/hooks.py

Qty not updating properly
changed hook to before validate
No
- Chrome
- Opera Mini
- Safari

fix: issue with qty

---

eseller_suite/eseller_suite/custom_script/sales_order/sales_order.py
eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_repository.py
eseller_suite/eseller_suite/report/amazon_itemwise_sales_report/amazon_itemwise_sales_report.js
eseller_suite/eseller_suite/report/amazon_itemwise_sales_report/amazon_itemwise_sales_report.json
eseller_suite/eseller_suite/report/amazon_itemwise_sales_report/amazon_itemwise_sales_report.py
eseller_suite/setup.py

Amazon Rate should be displayed in Sales Order and Sales Invoice (Item Price + Item Tax)
- Modified the code to set the required values
- Added a new report to view the amazon rate and amount

feat: marking amazon rate and itemwise report based on it

---

eseller_suite/eseller_suite/custom_script/sales_order/sales_order.py
eseller_suite/eseller_suite/doctype/amazon_failed_invoice_record/amazon_failed_invoice_record.js
eseller_suite/eseller_suite/doctype/amazon_failed_invoice_record/amazon_failed_invoice_record.json
eseller_suite/eseller_suite/doctype/amazon_failed_invoice_record/amazon_failed_invoice_record.py
eseller_suite/eseller_suite/doctype/amazon_failed_invoice_record/test_amazon_failed_invoice_record.py
eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_repository.py
eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_sp_api_settings.json

When Syncing Amazon Orders, Invoices are getting submitted without stock
Set temporary warehouse transfer as optional
Added check of stock before submitting sales invoice

fix: si submitting without stock

---

eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_repository.py

Added script to Bulk add Stock Entries for Sales Invoices

fix: stock entry creation against sales invoices

---

eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_repository.py

Handle the multiple return item correctly
Corrected the method to handle multiple return item
No
no
- Chrome

fix:corrected the method to handle multiple return items

---

eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_repository.py

- Solve the issue of tax being duplicated in return invoice
- mainted the recoe 
-No
- Chrome

Dev ajmal return si

---

eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_repository.py

Missing charges leaving ledgers not zeroed out
There were some fees that were not getting added in return invoices due to how it was being processed, updated the code to handle everything into one single invoice as well as cancel and create a new credit note in case of any updates
Return Invoice (Credit Note) creation via amazon order sync
Yes, no longer will multiple return invoices (credit notes) be created against a single invoice, rather, all the data will be converted into a singular return invoice containing all the item detail (each item from refund events as a separate row, regardless of whether they are the same or not), taxes, charges and fees.
- Chrome: Yes
- Opera Mini
- Safari

fix: missing charges in return invoices

---

eseller_suite/eseller_suite/custom_script/sales_order/sales_order.py

- Temporary stock is getting created for cancelled orders.
- Temporary stock reference is wrong
- Temporary stock transfer time not in line with sales

fix: made temporary stock transfer in line with the sales times

---

eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_repository.py

Clearly and concisely describe the feature.
Analyse and attach the design documentation
Describe your code changes in detail for reviewers.
Post the output screenshots, if a UI is affected or added due to this feature.
List out the areas affected by your code changes.
Mention Yes or No. If Yes, provide the appropriate explanation.
- Chrome
- Opera Mini
- Safari

fix: fee type was being appended where tds type should be

---

eseller_suite/eseller_suite/doctype/amazon_payment_entry/amazon_payment_entry.js
eseller_suite/eseller_suite/doctype/amazon_payment_entry/amazon_payment_entry.json
eseller_suite/eseller_suite/report/amazon_itemwise_sales_report/amazon_itemwise_sales_report.js
eseller_suite/eseller_suite/report/amazon_itemwise_sales_report/amazon_itemwise_sales_report.py

- AMZ Payment Entry getting stuck due to timeouts and some such
- SKU Wise report should be based on Invoice

Sync issues and SKU wise repot
