efeone/eseller_suite

- eseller_suite/eseller_suite/custom_script/sales_order/sales_order.py
- eseller_suite/hooks.py
Create a Sales Invoice upon submitting a Sales Order of each order.
No.
- Chrome
> feat: Create a Sales Invoice upon submitting a Sales Order of each order.

- eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_repository.py
Delivery date validation was throwing errors
set the delivery date to transaction date in case the shipping date clashed
No
- Chrome - Yes
- Opera Mini
- Safari
> fix: delivery date validation issue

- eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_repository.py
- eseller_suite/setup.py
There are cases where the same Item will have AFN and MFN. To handle this, we will add a reference to the actual item so that the actual will be used wherever the item is referenced.
- Added a custom field on Item Master, Actual Item, Link to Item
- On Creation of Sales Order from Amazon APIs, while finding Item with Amazon Item Code, checked whether the Item has any actual item. If item exists, then the item will be the actual item. Otherwise, the fetched item will be used.
- Fixed an issue with a non-existing variable
Amazon Repository
Item (customisation)
Yes, Items with actual item referenced in it will have the actual item used in so, si etc
- Chrome - Yes
- Opera Mini
- Safari
> feat: Bifurcated MFN and AFN Item to single Item

- eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_repository.py
Customer Name must be the Order ID they are created against
Changed the customer creation code to set customer name as the order ID
Customer Creation 
No
- Chrome - Yes
- Opera Mini
- Safari
> chore: set customer name to be the order ID

- eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_repository.py
- eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_sp_api_settings.json
- eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_sp_api_settings.py
- eseller_suite/hooks.py
- A daily scheduler to ensure that data from the previous day will be synced properly
- Making amazon state mapping optional
Hooks > Scheduler
Amazon SP API settings
Yes. Hourly scheduler won't work at midnight and state mapping is now optional
- Chrome
- Opera Mini
- Safari
> feat: daily scheduler and amazon state mapping config

- eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_sp_api_settings.py
- eseller_suite/hooks.py
Currently, Amazon orders are fetched based on GMT time (+00:00), but since we're using Indian Standard Time (IST, +05:30) for syncing, this time difference was causing some orders to be missed. Need to implement a solution to handle the timezone difference more accurately
Hourly Scheduler getting timed out
Converted current time in the system to GMT + 0 time 
Changed Hourly scheduler to Hourly Long scheduler
Hourly Scheduler for syncing amazon data
Yes, the hourly scheduler will now adjust the date depending on system timezone
- Chrome - Yes
- Opera Mini
- Safari
> fix: handling timezone difference and scheduler timeout

- eseller_suite/eseller_suite/doctype/amazon_payment_entry/amazon_payment_entry.py
- eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_repository.py
- eseller_suite/eseller_suite/doctype/eseller_settings/eseller_settings.json
- Added an option to record unreferenced Income and Expenses in Amazon Payment Entry
- Added exception handling when saving and submitting a sales order, as well as creating a return invoice
- Changed the code of creating return invoice to use actual item
- Amazon Payment Entry
No
- Chrome
- Opera Mini
- Safari
> Amz payment entry chore

- eseller_suite/eseller_suite/custom_script/purchase_receipt/purchase_receipt.py
Duplicates validation triggering on empty inputs
Removed empty data from the duplicates list
Purchase Receipt custom script
No
- Chrome
- Opera Mini
- Safari
> fix: empty check in duplicates validation

- eseller_suite/eseller_suite/doctype/amazon_payment_entry/amazon_payment_entry.py
Cannot submit amazon payment entry to create JV. The error being shown s that one row in the created JV has zero credit or debit.
The Reserve row update for JV was not updated properly
Amazon Payment Entry
No
- Chrome
- Opera Mini
- Safari
> fix: zero debit or credit in amz payment entry

- eseller_suite/eseller_suite/custom_script/sales_order/sales_order.py
- eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_repository.py
- eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_sp_api_settings.json
- eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_sp_api_settings.py
- eseller_suite/eseller_suite/report/amazon_sales_report/amazon_sales_report.json
- eseller_suite/eseller_suite/report/amazon_sales_report/amazon_sales_report.py
- eseller_suite/setup.py
When a Sales Order is created via amazon sync, items are moved to a warehouse set in Amazon SP API Settings and the source warehouse in the sales order is set to the same
Optimized Amazon Sales Report
Amazon SP API Settings
No
- Chrome
- Opera Mini
- Safari
> feat: moving stock to temporary and amazon sales report optimization

- eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_repository.py
Should check for existence of Taxes and Charges before submitting an so and si being created.
checked the data before so submission is done
Amazon SO sync
Yes, sales orders without taxes and charges will not be submitted.
- Chrome - Yes
- Opera Mini
- Safari
> chore: check for taxes and charges before submitting so

- eseller_suite/eseller_suite/doctype/amazon_payment_entry/amazon_payment_entry.py
- eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_repository.py
- eseller_suite/eseller_suite/doctype/cancelled_order_items/cancelled_order_items.json
- eseller_suite/eseller_suite/doctype/cancelled_order_items/cancelled_order_items.py
- eseller_suite/setup.py
When some (not all) items in an order is cancelled, it has to be recorded as cancelled separately
Unlike fully cancelled orders, cancelled items in an order will not be recorded in Cacnelled Items table in Sales Order
No
- Chrome - Yes
- Opera Mini
- Safari
> handling partial cancelled orders, amazon easy ship charges return marked on return invoice

- eseller_suite/eseller_suite/custom_script/purchase_receipt/purchase_receipt.py
- eseller_suite/eseller_suite/doctype/eseller_serial_no/eseller_serial_no.json
- eseller_suite/hooks.py
Serial Nos should be deleted when a PR is cancelled
Cleaned up the alert messages to only appear when needed
eSeller Serial No. Updation
No
- Chrome
- Opera Mini
- Safari
> Delete serial nos

- eseller_suite/eseller_suite/doctype/amazon_payment_entry/amazon_payment_entry.py
Amazon Payment Entry trying to link cancelled invoices
Added docstatus filter
> fix: ensuring cancelled sales invoices won't be linked with payments

- eseller_suite/eseller_suite/custom_script/sales_order/sales_order.py
- eseller_suite/eseller_suite/doctype/amazon_payment_entry/amazon_payment_entry.json
- eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_repository.py
- eseller_suite/patches.txt
- eseller_suite/patches/delete_unlinked_temporary_stock_tranfers.py
Major stock inconsistencies caused by temporary stock transfer
- Patch to delete unlinked temporary stock transfers
- Confirmation for temporary stock transfer before so submission
- Deleting temporary stock transfers after deletion of corresponding sales orders
- Warehouses in Returns should be based on the fulfillment channel
Amazon Repository
No
- Chrome - Yes
- Opera Mini
- Safari
> fix: stock issues due to temporary transfers

- eseller_suite/eseller_suite/doctype/amazon_payment_entry/amazon_payment_entry.js
- eseller_suite/eseller_suite/doctype/amazon_payment_entry/amazon_payment_entry.py
Missing Customer and Sales Invoice links for Ready to Process lines in Amazon Payment Entry. This was due to Invoices and SOs being deleted but the JVs of replaced orders being left behind.
Added button to unset ready to process so the invoices can be fetched again. 
Updated invoicing fetching code to ensure customer and sales invoice IDs are set
> fix: links missing for replaced order references in amz payment entry

- eseller_suite/eseller_suite/custom_script/sales_order/sales_order.py
- eseller_suite/eseller_suite/doctype/amazon_payment_entry/amazon_payment_entry.json
- eseller_suite/eseller_suite/doctype/amazon_payment_entry/amazon_payment_entry.py
- eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_repository.py
- eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_sp_api_settings.json
- Temporary Stock Transfer Cancellation on order cancel status causing link issues
- Need to handle:
- - Refunds without Returns in amz payment entry
- - mfn postage fee in amz payment entry
- issue with concatenation in sync
- Updated script to remove link before cancelling and deleting the temporary stock transfer
- Added an option to set all remaining refunds in the amz payment entry to be set as ready to process
- created a separate jv for mfn postage fees
- updated script to handle none values in concatenation
- other mining fixes
> March sync issue2

- eseller_suite/eseller_suite/doctype/amazon_sp_api_settings/amazon_repository.py
- Order not getting synced
- Changed description formatting so that order id will be used if seller sku is none
- Checked for existence of Seller SKU before item is fetched
> fix: use order_id in taxes and charges description of seller_ksu is none

- eseller_suite/eseller_suite/custom_script/sales_order/sales_order.py
- eseller_suite/eseller_suite/doctype/amazon_payment_entry/amazon_payment_entry.py
- Bulk submission of sales orders caused orders that should not be submitted to be submitted as well.
- Added validation to ensure only valid amazon sales orders can be submitted
- Added script to ensure cancelled sales invoices won't be linked in an amazon payment entry
> fix: added validation for amz so submission

- eseller_suite/eseller_suite/custom_script/sales_order/sales_order.py
- Sync trying to cancel unsubmitted stock entries
- Cancel only if the stock entry is submitted
> fix: cancel stock transfer only if submitted against so
